language: ruby
rvm:
  - 2.0.0
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - psql -U postgres -c "create extension postgis"
# script:
#   - RAILS_ENV=test bundle exec rake db:migrate --trace
#   - bundle exec rake
script:
  - bundle exec rake db:test:prepare
  - bundle exec rake db:travis_after_migrate
  - bundle exec rake